version: "3"
services:
  api:
    volumes: 
      - .:/sourcecode
    build: .
    command: node index.js
    ports:
      - "7000:7000"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: mongo:27017
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"